from __future__ import annotations
from typing import Protocol, Literal
from dataclasses import dataclass
from .models import *
from .errors import ErrorCode

class AuthService(Protocol):
    async def register(self, email: str, password: str, display_name: str) -> LoginResult: ...
    async def login(self, email: str, password: str) -> LoginResult: ...
    async def authenticate(self, session_token: str) -> SessionPrincipal: ...
    async def validate_csrf(self, principal: SessionPrincipal, token: str) -> None: ...
    async def logout(self, principal: SessionPrincipal) -> None: ...
    async def me(self, principal: SessionPrincipal) -> Me: ...

class ProjectService(Protocol):
    async def list_projects(self, principal: SessionPrincipal, page: PageRequest) -> Page[Project]: ...
    async def create_project(self, principal: SessionPrincipal, name: str) -> Project: ...
    async def delete_project(self, ctx: RequestContext) -> None: ...
    async def list_project_types(self, ctx: RequestContext) -> Page[ProjectType]: ...
    async def create_project_type(self, ctx: RequestContext, name: str) -> ProjectType: ...
    async def list_project_types(self, ctx: RequestContext) -> Page[ProjectType]: ...
    async def create_project_type(self, ctx: RequestContext, name: str) -> ProjectType: ...
    async def authorize(self, principal: SessionPrincipal, project_id: Id, required_role: Role = "member") -> RequestContext: ...

class DocumentService(Protocol):
    async def list_documents(self, ctx: RequestContext, page: PageRequest) -> Page[Document]: ...
    async def list_records(self, ctx: RequestContext, document_id: Id, page: PageRequest) -> Page[RecordSummary]: ...
    async def submit_upload(self, ctx: RequestContext, upload: UploadInput) -> Job: ...
    async def mutate_document(self, ctx: RequestContext, document_id: Id, action: Literal["activate", "deactivate", "delete"]) -> Job: ...

class SourceService(Protocol):
    async def read_record(self, ctx: RequestContext, record_id: Id, page: PageRequest) -> RecordPage: ...
    async def read_source(self, ctx: RequestContext, request: SourceRequest) -> SourcePage: ...
    async def get_status(self, ctx: RequestContext) -> ProjectStatus: ...
    async def get_overview(self, ctx: RequestContext) -> Overview: ...
    async def get_timeline(self, ctx: RequestContext, page: PageRequest) -> Page[TimelineRecord]: ...
    async def get_filters(self, ctx: RequestContext) -> FilterOptions: ...

class AdministrationService(Protocol):
    async def list_members(self, ctx: RequestContext, page: PageRequest) -> Page[Member]: ...
    async def set_member_by_email(self, ctx: RequestContext, email: str, role: Role) -> Member: ...
    async def set_member(self, ctx: RequestContext, user_id: Id, role: Role) -> Member: ...
    async def remove_member(self, ctx: RequestContext, user_id: Id) -> None: ...
    async def list_people(self, ctx: RequestContext, page: PageRequest) -> Page[Person]: ...
    async def list_original_documents(self, ctx: RequestContext, page: PageRequest) -> Page[OriginalDocument]: ...
    async def get_original_document(self, ctx: RequestContext, document_id: Id) -> OriginalDocumentContent: ...
    async def search_identity_mappings(self, ctx: RequestContext, query: str, page: PageRequest) -> Page[IdentityMapping]: ...
    async def associate_person(self, ctx: RequestContext, input: PersonInput) -> Person: ...
    async def erase_person(self, ctx: RequestContext, person_id: Id) -> Job: ...
    async def list_jobs(self, ctx: RequestContext, page: PageRequest) -> Page[Job]: ...
    async def get_job(self, ctx: RequestContext, job_id: Id) -> Job: ...
    async def retry_job(self, ctx: RequestContext, job_id: Id) -> Job: ...

class ConversationService(Protocol):
    async def create(self, ctx: RequestContext, title: str | None = None) -> Conversation: ...
    async def list(self, ctx: RequestContext, page: PageRequest) -> Page[Conversation]: ...
    async def messages(self, ctx: RequestContext, conversation_id: Id, page: PageRequest) -> Page[Message]: ...
    async def begin_chat(self, ctx: RequestContext, input: ChatInput) -> BeginChatResult: ...
    async def release_answer(self, ctx: RequestContext, attempt: ChatAttempt, candidate: ReviewedCandidate) -> Answer: ...
    async def fail_chat(self, ctx: RequestContext, attempt: ChatAttempt, code: ErrorCode) -> None: ...
    async def get_answer(self, ctx: RequestContext, answer_id: Id) -> Answer: ...
    async def get_receipt(self, ctx: RequestContext, answer_id: Id, receipt_id: Id) -> Receipt: ...

class EvidenceReader(Protocol):
    async def read_record(self, ctx: ReadContext, record_id: Id, page: PageRequest) -> MemoryPage: ...
    async def read_memory(self, ctx: ReadContext, memory_id: Id) -> Memory: ...
    async def expand_context(self, ctx: ReadContext, ref: EvidenceRef, before: int = 2, after: int = 2) -> SourcePage: ...
    async def normalize_query(self, ctx: ReadContext, text: str) -> NormalizedText: ...
    async def make_receipt(self, ctx: ReadContext, ref: EvidenceRef) -> Receipt: ...

class RetrievalRepository(Protocol):
    async def lexical_candidates(self, ctx: ReadContext, normalized_query: str, filters: SearchFilters, limit: int) -> list[CandidateRef]: ...
    async def validate_candidates(self, ctx: ReadContext, candidates: list[CandidateRef], filters: SearchFilters) -> CandidateCheck: ...
    async def read_history(self, ctx: ReadContext, query: HistoryQuery, page: PageRequest) -> HistoryPage: ...

class IntelligenceService(Protocol):
    async def search_memory(self, ctx: RequestContext, input: SearchInput) -> SearchPage: ...
    async def search_agent_memory(self, ctx: RequestContext, input: SearchInput) -> SearchPage: ...
    async def search_sources(self, ctx: RequestContext, input: SearchInput) -> SearchPage: ...
    async def get_decision_history(self, ctx: ReadContext, query: HistoryQuery, page: PageRequest) -> HistoryPage: ...
    async def answer(self, ctx: RequestContext, input: AnswerInput) -> ReviewedCandidate: ...

class ArtifactRepository(Protocol):
    async def load_staged_record(self, cap: JobCapability, ref: RecordVersionRef) -> StagedRecord: ...
    async def published_context(self, cap: JobCapability) -> WorkReadContext: ...
    async def load_rebuild_plan(self, cap: JobCapability, plan_id: Id) -> RebuildPlan: ...
    async def load_staged_artifacts(self, cap: JobCapability, artifact_key: str) -> StagedArtifacts | None: ...
    async def stage_artifacts(self, cap: JobCapability, artifact_key: str, batch: ArtifactBatch) -> StagedArtifacts: ...
    async def release_overview(self, cap: JobCapability, input: OverviewCandidate) -> Overview: ...

class MaintenanceHandlers(Protocol):
    async def process_record(self, cap: JobCapability, ref: RecordVersionRef) -> MaintenanceResult: ...
    async def rebuild_affected(self, cap: JobCapability, plan: RebuildPlan) -> MaintenanceResult: ...
    async def remove_index_entries(self, cap: JobCapability, entry_ids: list[Id]) -> MaintenanceResult: ...
    async def reconcile(self, cap: JobCapability) -> ReconciliationReport: ...

class JobCoordinator(Protocol):
    async def claim(self, worker_id: Id, kinds: list[JobKind]) -> JobLease | None: ...
    async def heartbeat(self, lease: JobLease) -> JobLease: ...
    async def advance(self, lease: JobLease, expected_stage: JobStage, next_stage: JobStage, counts: dict[str, int]) -> JobLease: ...
    async def capability(self, lease: JobLease, stage: JobStage) -> JobCapability: ...
    async def publish(self, lease: JobLease, results: list[MaintenanceResult]) -> Job: ...
    async def fail(self, lease: JobLease, code: str, retryable: bool) -> Job: ...

class IndexOperationLedger(Protocol):
    async def prepare(self, cap: JobCapability, input: IndexOperationInput) -> OperationTicket: ...
    async def start(self, cap: JobCapability, operation_id: Id) -> None: ...
    async def report(self, ticket: OperationTicket, outcome: IndexOutcome) -> None: ...
    async def list_operations(self, cap: JobCapability, page: PageRequest) -> Page[IndexOperation]: ...
    async def get_entries(self, cap: JobCapability, entry_ids: list[Id]) -> list[IndexEntry]: ...

class PrivacyDetector(Protocol):
    async def detect(self, input: PrivacyDetectionInput) -> PrivacyDetectionResult: ...

@dataclass
class Services:
    auth: AuthService
    projects: ProjectService
    documents: DocumentService
    sources: SourceService
    administration: AdministrationService
    conversations: ConversationService
    intelligence: IntelligenceService
