/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projects */
        get: operations["projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_projects__p__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Types */
        get: operations["project_types_api_projects__p__types_get"];
        put?: never;
        /** Create Project Type */
        post: operations["create_project_type_api_projects__p__types_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Documents */
        get: operations["documents_api_projects__p__documents_get"];
        put?: never;
        /** Upload */
        post: operations["upload_api_projects__p__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/documents/{id}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Records */
        get: operations["records_api_projects__p__documents__id__records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/documents/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Route */
        post: operations["route_api_projects__p__documents__id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/documents/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Route */
        post: operations["route_api_projects__p__documents__id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Route */
        delete: operations["route_api_projects__p__documents__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Record */
        get: operations["record_api_projects__p__records__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/sources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source */
        get: operations["source_api_projects__p__sources__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_api_projects__p__search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filters */
        get: operations["filters_api_projects__p__filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_projects__p__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_projects__p__overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Timeline */
        get: operations["timeline_api_projects__p__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Conversations */
        get: operations["conversations_api_projects__p__conversations_get"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_api_projects__p__conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Messages */
        get: operations["messages_api_projects__p__conversations__id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_projects__p__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/answers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Answer */
        get: operations["answer_api_projects__p__answers__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/answers/{id}/receipts/{receipt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Receipt */
        get: operations["receipt_api_projects__p__answers__id__receipts__receipt_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Members */
        get: operations["members_api_projects__p__members_get"];
        put?: never;
        /** Set Member */
        post: operations["set_member_api_projects__p__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/members/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_api_projects__p__members__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** People */
        get: operations["people_api_projects__p__people_get"];
        put?: never;
        /** Associate */
        post: operations["associate_api_projects__p__people_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/original-documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Original Documents */
        get: operations["original_documents_api_projects__p__original_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/original-documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Original Document */
        get: operations["original_document_api_projects__p__original_documents__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/identity-mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identity Mappings */
        get: operations["identity_mappings_api_projects__p__identity_mappings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/people/{id}/erase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Erase */
        post: operations["erase_api_projects__p__people__id__erase_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/stale-reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stale Reviews */
        get: operations["stale_reviews_api_projects__p__stale_reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/stale-reviews/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Stale Review */
        post: operations["approve_stale_review_api_projects__p__stale_reviews__id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/stale-reviews/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Stale Review */
        post: operations["reject_stale_review_api_projects__p__stale_reviews__id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/privacy/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Privacy Diagnostics */
        get: operations["privacy_diagnostics_api_projects__p__privacy_diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/privacy/diagnostics/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Privacy */
        post: operations["resolve_privacy_api_projects__p__privacy_diagnostics__id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs */
        get: operations["jobs_api_projects__p__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job */
        get: operations["job_api_projects__p__jobs__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{p}/jobs/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_api_projects__p__jobs__id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Answer */
        Answer: {
            /** Id */
            id: string;
            /** Conversation Id */
            conversation_id: string;
            /** Request Id */
            request_id: string;
            /** Claims */
            claims: components["schemas"]["Claim"][];
            /** Receipts */
            receipts: components["schemas"]["Receipt"][];
            coverage: components["schemas"]["Coverage"];
            /** Cannot Establish */
            cannot_establish: ("no_evidence" | "incomplete_coverage" | "unresolved_conflict" | "ambiguous_person" | "review_rejected") | null;
            snapshot: components["schemas"]["Snapshot"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Body_upload_api_projects__p__documents_post */
        Body_upload_api_projects__p__documents_post: {
            /** File */
            file: string;
            /** Record Type */
            record_type: string;
        };
        /** ChatInput */
        ChatInput: {
            /** Question */
            question: string;
            /** Conversation Id */
            conversation_id: string;
            /** Request Id */
            request_id: string;
        };
        /** Claim */
        Claim: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Receipt Ids */
            receipt_ids: string[];
            /** Status */
            status: ("suggestion" | "commitment" | "superseded" | "corrected" | "conflict" | "unknown") | null;
            /** Scope */
            scope: string | null;
            effective_at: components["schemas"]["SourceTime"] | null;
        };
        /** Contact */
        Contact: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "email" | "phone" | "postal_address";
            /** Value */
            value: string;
        };
        /** Conversation */
        Conversation: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Owner User Id */
            owner_user_id: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ConversationInput */
        ConversationInput: {
            /**
             * Title
             * @default New Chat
             */
            title: string;
        };
        /** Coverage */
        Coverage: {
            /**
             * State
             * @enum {string}
             */
            state: "complete" | "partial" | "insufficient";
            /** Records */
            records: components["schemas"]["RecordCoverage"][];
            /** Limitations */
            limitations: components["schemas"]["Limitation"][];
        };
        /** Document */
        Document: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Record Type */
            record_type: string;
            /**
             * Ai Status
             * @enum {string}
             */
            ai_status: "active" | "inactive";
            /**
             * Processing State
             * @enum {string}
             */
            processing_state: "pending" | "running" | "completed" | "failed";
            /** Record Count */
            record_count: number;
            /** Records Url */
            records_url: string;
            /** Latest Job Id */
            latest_job_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** EvidenceRef */
        EvidenceRef: {
            /** Project Id */
            project_id: string;
            /** Original Doc Id */
            original_doc_id: string;
            /** Record Id */
            record_id: string;
            /** Record Version */
            record_version: number;
            /** Span Ids */
            span_ids: string[];
        };
        /** FilterOptions */
        FilterOptions: {
            /** Record Types */
            record_types: string[];
            /** Documents */
            documents: components["schemas"]["Option"][];
            /** Topics */
            topics: components["schemas"]["Option"][];
            /** People */
            people: components["schemas"]["Option"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IdentityMapping */
        IdentityMapping: {
            /** Pseudonym */
            pseudonym: string;
            /** Display Name */
            display_name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "client" | "employee";
            /** Contacts */
            contacts: components["schemas"]["Contact"][];
            /**
             * State
             * @enum {string}
             */
            state: "active" | "erasing";
        };
        /** Job */
        Job: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "ingest" | "activate" | "deactivate" | "delete_document" | "erase_person" | "rebuild_aggregate" | "reconcile";
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "running" | "completed" | "failed";
            /**
             * Stage
             * @enum {string}
             */
            stage: "received" | "parsed" | "privacy_ready" | "extracted" | "indexed" | "published" | "invalidating" | "inventory" | "draining" | "sanitizing" | "rebuilding" | "removing_index" | "verifying" | "done";
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Error Code */
            error_code: string | null;
            /** Retryable */
            retryable: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** Limitation */
        Limitation: {
            /**
             * Code
             * @enum {string}
             */
            code: "no_evidence" | "unread_chunks" | "history_incomplete" | "conflicting_evidence" | "budget_exhausted" | "ambiguous_person" | "unknown_effective_time";
            /** Record Ids */
            record_ids: string[];
        };
        /** LoginInput */
        LoginInput: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** Me */
        Me: {
            /** User Id */
            user_id: string;
            /** Display Name */
            display_name: string;
            /** Csrf Token */
            csrf_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** Member */
        Member: {
            /** User Id */
            user_id: string;
            /** Display Name */
            display_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "member" | "admin";
            /**
             * Granted At
             * Format: date-time
             */
            granted_at: string;
        };
        /** MemberInput */
        MemberInput: {
            /** User Id */
            user_id?: string | null;
            /** Email */
            email?: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "member" | "admin";
        };
        /** Message */
        Message: {
            /** Id */
            id: string;
            /** Conversation Id */
            conversation_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /**
             * State
             * @enum {string}
             */
            state: "available" | "pending" | "unavailable" | "failed";
            /** Text */
            text: string | null;
            /** Answer Id */
            answer_id: string | null;
            /** Unavailable Reason */
            unavailable_reason: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Option */
        Option: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** OriginalDocument */
        OriginalDocument: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Record Type */
            record_type: string;
            /** Processed Filename */
            processed_filename: string;
            /** Processed Sources */
            processed_sources: components["schemas"]["ProcessedDocumentSource"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** OriginalDocumentContent */
        OriginalDocumentContent: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Record Type */
            record_type: string;
            /** Processed Filename */
            processed_filename: string;
            /** Processed Sources */
            processed_sources: components["schemas"]["ProcessedDocumentSource"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Processed Content */
            processed_content: string;
        };
        /** Overview */
        Overview: {
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "ready" | "failed" | "unavailable";
            /** Id */
            id: string | null;
            /** Claims */
            claims: components["schemas"]["Claim"][];
            /** Receipts */
            receipts: components["schemas"]["Receipt"][];
            coverage: components["schemas"]["Coverage"] | null;
            snapshot: components["schemas"]["Snapshot"];
            /** Error Code */
            error_code: string | null;
        };
        /** Page[Conversation] */
        Page_Conversation_: {
            /** Items */
            items: components["schemas"]["Conversation"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[Document] */
        Page_Document_: {
            /** Items */
            items: components["schemas"]["Document"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[IdentityMapping] */
        Page_IdentityMapping_: {
            /** Items */
            items: components["schemas"]["IdentityMapping"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[Job] */
        Page_Job_: {
            /** Items */
            items: components["schemas"]["Job"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[Member] */
        Page_Member_: {
            /** Items */
            items: components["schemas"]["Member"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[Message] */
        Page_Message_: {
            /** Items */
            items: components["schemas"]["Message"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[OriginalDocument] */
        Page_OriginalDocument_: {
            /** Items */
            items: components["schemas"]["OriginalDocument"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[Person] */
        Page_Person_: {
            /** Items */
            items: components["schemas"]["Person"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[PrivacyDiagnostic] */
        Page_PrivacyDiagnostic_: {
            /** Items */
            items: components["schemas"]["PrivacyDiagnostic"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[ProjectType] */
        Page_ProjectType_: {
            /** Items */
            items: components["schemas"]["ProjectType"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[Project] */
        Page_Project_: {
            /** Items */
            items: components["schemas"]["Project"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[RecordSummary] */
        Page_RecordSummary_: {
            /** Items */
            items: components["schemas"]["RecordSummary"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[StaleReview] */
        Page_StaleReview_: {
            /** Items */
            items: components["schemas"]["StaleReview"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[TimelineRecord] */
        Page_TimelineRecord_: {
            /** Items */
            items: components["schemas"]["TimelineRecord"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Person */
        Person: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "client" | "employee";
            /** Contacts */
            contacts: components["schemas"]["Contact"][];
            /**
             * State
             * @enum {string}
             */
            state: "active" | "erasing";
        };
        /** PersonInput */
        PersonInput: {
            /** Person Id */
            person_id?: string | null;
            /** Display Name */
            display_name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "client" | "employee";
            /** Contacts */
            contacts: components["schemas"]["Contact"][];
        };
        /** PrivacyDiagnostic */
        PrivacyDiagnostic: {
            /** Id */
            id: string;
            /** Record Id */
            record_id: string;
            /** Record Version */
            record_version: number;
            /** Span Id */
            span_id: string;
            /** Start */
            start?: number | null;
            /** End */
            end?: number | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "person" | "organization" | "role" | "contact" | "personal_identifier" | "contextual_circumstance" | "uncertain";
            /** Reason */
            reason: string;
            /**
             * State
             * @enum {string}
             */
            state: "open" | "resolved";
            /** Resolution */
            resolution?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PrivacyResolutionInput */
        PrivacyResolutionInput: {
            /** Resolution */
            resolution: string;
        };
        /** ProcessedDocumentSource */
        ProcessedDocumentSource: {
            /** Record Id */
            record_id: string;
            /** Record Version */
            record_version: number;
            /** Title */
            title: string;
            /** Processed Content Url */
            processed_content_url: string;
        };
        /** Project */
        Project: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "member" | "admin";
        };
        /** ProjectInput */
        ProjectInput: {
            /** Name */
            name: string;
        };
        /** ProjectStatus */
        ProjectStatus: {
            /** Project Id */
            project_id: string;
            /** Eligible Documents */
            eligible_documents: number;
            /** Eligible Records */
            eligible_records: number;
            /** Operational Job Counts */
            operational_job_counts: {
                [key: string]: number;
            } | null;
            /** Write Barrier */
            write_barrier: boolean;
            snapshot: components["schemas"]["Snapshot"];
        };
        /** ProjectType */
        ProjectType: {
            /** Name */
            name: string;
        };
        /** ProjectTypeInput */
        ProjectTypeInput: {
            /** Name */
            name: string;
        };
        /** Receipt */
        Receipt: {
            /** Id */
            id: string;
            evidence_ref: components["schemas"]["EvidenceRef"];
            /** Quote */
            quote: string;
            /** Source Url */
            source_url: string;
            /** Source Title */
            source_title: string;
            /** Record Type */
            record_type: string;
            source_time: components["schemas"]["SourceTime"];
            /** Source Locations */
            source_locations: components["schemas"]["SourceLocation"][];
        };
        /** RecordCoverage */
        RecordCoverage: {
            /** Record Id */
            record_id: string;
            /** Record Version */
            record_version: number;
            /** Total Chunks */
            total_chunks: number;
            /** Supplied Chunk Ids */
            supplied_chunk_ids: string[];
            /** Complete */
            complete: boolean;
        };
        /** RecordPage */
        RecordPage: {
            record: components["schemas"]["RecordSummary"];
            /** Spans */
            spans: components["schemas"]["Span"][];
            /** Returned Chunk Ids */
            returned_chunk_ids: string[];
            /** Total Chunks */
            total_chunks: number;
            /** Next Cursor */
            next_cursor: string | null;
            /** Complete */
            complete: boolean;
            snapshot: components["schemas"]["Snapshot"];
        };
        /** RecordSummary */
        RecordSummary: {
            /** Record Id */
            record_id: string;
            /** Original Doc Id */
            original_doc_id: string;
            /** Record Version */
            record_version: number;
            /** Title */
            title: string;
            /** Record Type */
            record_type: string;
            source_time: components["schemas"]["SourceTime"];
            /** Total Chunks */
            total_chunks: number;
        };
        /** RegisterInput */
        RegisterInput: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name: string;
        };
        /** SearchBody */
        SearchBody: {
            /** Query */
            query: string;
            filters: components["schemas"]["SearchFilters"];
            /** Cursor */
            cursor?: string | null;
            /**
             * Limit
             * @default 25
             */
            limit: number;
        };
        /** SearchFilters */
        SearchFilters: {
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
            /** Record Type */
            record_type?: string | null;
            /** Original Doc Id */
            original_doc_id?: string | null;
            /** Topic Id */
            topic_id?: string | null;
            /** Person Id */
            person_id?: string | null;
        };
        /** SearchHit */
        SearchHit: {
            record: components["schemas"]["RecordSummary"];
            /** Description */
            description: string;
            /** Snippet */
            snippet: string;
            /** Matched Span Ids */
            matched_span_ids: string[];
        };
        /** SearchPage */
        SearchPage: {
            /** Items */
            items: components["schemas"]["SearchHit"][];
            /** Next Cursor */
            next_cursor: string | null;
            snapshot: components["schemas"]["Snapshot"];
        };
        /** Snapshot */
        Snapshot: {
            /** Corpus Generation */
            corpus_generation: number;
            /** Privacy Generation */
            privacy_generation: number;
        };
        /** SourceLocation */
        SourceLocation: {
            /** Line Start */
            line_start: number | null;
            /** Line End */
            line_end: number | null;
            /** Paragraph */
            paragraph: number | null;
            /** Message Ordinal */
            message_ordinal: number | null;
            /** Turn Ordinal */
            turn_ordinal: number | null;
            /** Timestamp Label */
            timestamp_label: string | null;
            /** Speaker Label */
            speaker_label?: string | null;
            /**
             * Provenance
             * @default original
             * @enum {string}
             */
            provenance: "original" | "quoted" | "forwarded";
        };
        /** SourcePage */
        SourcePage: {
            record: components["schemas"]["RecordSummary"];
            /** Spans */
            spans: components["schemas"]["Span"][];
            /** Highlighted Span Ids */
            highlighted_span_ids: string[];
            /** Next Cursor */
            next_cursor: string | null;
            /** Previous Cursor */
            previous_cursor: string | null;
            snapshot: components["schemas"]["Snapshot"];
        };
        /** SourceTime */
        SourceTime: {
            /** Value */
            value: string | null;
            /**
             * Precision
             * @enum {string}
             */
            precision: "unknown" | "year" | "month" | "day" | "instant";
            /** Timezone */
            timezone: string | null;
        };
        /** Span */
        Span: {
            /** Span Id */
            span_id: string;
            /** Ordinal */
            ordinal: number;
            /** Text */
            text: string;
            source_location: components["schemas"]["SourceLocation"];
        };
        /** StaleReview */
        StaleReview: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "replacement" | "cancellation" | "correction" | "reinstatement";
            /** Scope */
            scope: string;
            /** Proposed Change */
            proposed_change: string;
            /** Reason */
            reason: string;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "approved" | "rejected";
            /** Stale Evidence */
            stale_evidence: components["schemas"]["Receipt"][];
            /** Marking Evidence */
            marking_evidence: components["schemas"]["Receipt"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Reviewed By */
            reviewed_by: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
        };
        /** TimelineRecord */
        TimelineRecord: {
            /** Project Id */
            project_id: string;
            /** Record Id */
            record_id: string;
            /** Original Doc Id */
            original_doc_id: string;
            /** Record Version */
            record_version: number;
            /** Title */
            title: string;
            /** Record Type */
            record_type: string;
            source_time: components["schemas"]["SourceTime"];
            /** Level1 Summary */
            level1_summary: string | null;
            /** Level2 Summary */
            level2_summary: string | null;
            /** Processed Content Url */
            processed_content_url: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    projects_api_projects_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Project_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__p__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_types_api_projects__p__types_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ProjectType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_type_api_projects__p__types_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectTypeInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectType"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    documents_api_projects__p__documents_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Document_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_projects__p__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_projects__p__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    records_api_projects__p__documents__id__records_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RecordSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_api_projects__p__documents__id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_api_projects__p__documents__id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_api_projects__p__documents__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_api_projects__p__records__id__get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_api_projects__p__sources__id__get: {
        parameters: {
            query: {
                version: number;
                span: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_projects__p__search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    filters_api_projects__p__filters_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterOptions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_projects__p__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_projects__p__overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeline_api_projects__p__timeline_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TimelineRecord_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conversations_api_projects__p__conversations_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Conversation_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_api_projects__p__conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    messages_api_projects__p__conversations__id__messages_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Message_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_projects__p__chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Answer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_api_projects__p__answers__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Answer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receipt_api_projects__p__answers__id__receipts__receipt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                receipt_id: string;
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    members_api_projects__p__members_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Member_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_member_api_projects__p__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_projects__p__members__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    people_api_projects__p__people_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Person_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    associate_api_projects__p__people_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    original_documents_api_projects__p__original_documents_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_OriginalDocument_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    original_document_api_projects__p__original_documents__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OriginalDocumentContent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    identity_mappings_api_projects__p__identity_mappings_get: {
        parameters: {
            query?: {
                q?: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_IdentityMapping_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    erase_api_projects__p__people__id__erase_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stale_reviews_api_projects__p__stale_reviews_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_StaleReview_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_stale_review_api_projects__p__stale_reviews__id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaleReview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_stale_review_api_projects__p__stale_reviews__id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaleReview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    privacy_diagnostics_api_projects__p__privacy_diagnostics_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PrivacyDiagnostic_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_privacy_api_projects__p__privacy_diagnostics__id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                p: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrivacyResolutionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivacyDiagnostic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jobs_api_projects__p__jobs_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Job_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_api_projects__p__jobs__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_api_projects__p__jobs__id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
